# Generated by Django 5.2.6 on 2025-09-12 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_emailsendratelimit'),
        ('jobs', '0004_jobbrowsehistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(blank=True, max_length=200, null=True, verbose_name='招聘单位名称')),
                ('job_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='岗位名称')),
                ('employment_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='用工方式')),
                ('has_staffing_quota', models.BooleanField(blank=True, null=True, verbose_name='是否属于正式人员编制')),
                ('category', models.CharField(blank=True, choices=[('管理岗位', '管理岗位'), ('专业技术岗位', '专业技术岗位'), ('工勤技能岗位', '工勤技能岗位')], max_length=50, null=True, verbose_name='岗位类别')),
                ('job_location', models.CharField(blank=True, max_length=200, null=True, verbose_name='工作地点')),
                ('num_positions', models.CharField(blank=True, max_length=50, null=True, verbose_name='招聘人数')),
                ('is_targeted_recruitment', models.BooleanField(blank=True, null=True, verbose_name='是否是定向招聘')),
                ('targeted_recruitment_scope', models.TextField(blank=True, null=True, verbose_name='定向招聘范围')),
                ('registration_methods', models.CharField(blank=True, max_length=200, null=True, verbose_name='报名方式')),
                ('registration_materials', models.TextField(blank=True, null=True, verbose_name='报名所需材料')),
                ('contacts', models.CharField(blank=True, max_length=100, null=True, verbose_name='联系人')),
                ('contact_methods', models.CharField(blank=True, max_length=200, null=True, verbose_name='联系方式')),
                ('job_experience_requirement', models.TextField(blank=True, null=True, verbose_name='工作经验要求')),
                ('min_job_experience_level', models.CharField(choices=[('不限', '不限'), ('应届生', '应届生'), ('1年以上', '1年以上'), ('3年以上', '3年以上'), ('5年以上', '5年以上'), ('10年以上', '10年以上')], default='不限', max_length=20, verbose_name='最低工作经验要求')),
                ('degree_requirement', models.TextField(blank=True, null=True, verbose_name='学历要求')),
                ('min_degree_level', models.CharField(choices=[('不限', '不限'), ('小学', '小学'), ('初中', '初中'), ('高中（含中专、技校、职高）', '高中（含中专、技校、职高）'), ('大专（含高职、高专）', '大专（含高职、高专）'), ('本科', '本科'), ('硕士', '硕士'), ('博士', '博士')], default='不限', max_length=20, verbose_name='最低学历要求')),
                ('major_requirement', models.TextField(blank=True, null=True, verbose_name='专业要求')),
                ('age_requirement', models.CharField(blank=True, max_length=100, null=True, verbose_name='年龄要求')),
                ('max_age_level', models.CharField(choices=[('不限', '不限'), ('25岁以下', '25岁以下'), ('30岁以下', '30岁以下'), ('35岁以下', '35岁以下'), ('40岁以下', '40岁以下'), ('45岁以下', '45岁以下'), ('50岁以下', '50岁以下'), ('55岁以下', '55岁以下'), ('60岁以下', '60岁以下'), ('65岁以下', '65岁以下')], default='不限', max_length=20, verbose_name='年龄上限要求')),
                ('graduation_status_requirement', models.CharField(blank=True, max_length=100, null=True, verbose_name='毕业时间/应届身份要求')),
                ('title_requirement', models.CharField(blank=True, max_length=100, null=True, verbose_name='职称要求')),
                ('job_skill_requirements', models.TextField(blank=True, null=True, verbose_name='工作技能要求')),
                ('political_status_requirement', models.CharField(blank=True, max_length=100, null=True, verbose_name='政治面貌要求')),
                ('certificate_requirement', models.TextField(blank=True, null=True, verbose_name='证书要求')),
                ('minimum_service_years_requirement', models.CharField(blank=True, max_length=100, null=True, verbose_name='最低服务年限要求')),
                ('gender_requirement', models.CharField(blank=True, max_length=50, null=True, verbose_name='性别要求')),
                ('other_requirement', models.TextField(blank=True, null=True, verbose_name='其他要求')),
                ('job_responsibilities', models.TextField(blank=True, null=True, verbose_name='岗位职责')),
                ('salary_and_benefits', models.TextField(blank=True, null=True, verbose_name='薪资待遇')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
            ],
            options={
                'verbose_name': '岗位信息',
                'verbose_name_plural': '岗位信息',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='招聘公告标题')),
                ('publish_date', models.DateField(blank=True, null=True, verbose_name='公告发布时间')),
                ('organization', models.CharField(blank=True, max_length=200, null=True, verbose_name='招聘单位名称')),
                ('application_start_date', models.DateField(blank=True, null=True, verbose_name='报名开始时间')),
                ('application_end_date', models.DateField(blank=True, null=True, verbose_name='报名截止时间')),
                ('category', models.CharField(blank=True, choices=[('公务员', '公务员'), ('事业单位', '事业单位'), ('教师招聘', '教师招聘'), ('医疗招聘', '医疗招聘'), ('银行招聘', '银行招聘'), ('国企招聘', '国企招聘'), ('三支一扶', '三支一扶'), ('招警', '招警'), ('选调生', '选调生'), ('大学生村官', '大学生村官'), ('公选遴选', '公选遴选'), ('基层工作者', '基层工作者'), ('军队文职', '军队文职'), ('公益性岗位', '公益性岗位')], max_length=50, null=True, verbose_name='招聘分类')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
            ],
            options={
                'verbose_name': '招聘公告',
                'verbose_name_plural': '招聘公告',
                'ordering': ['-publish_date', '-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='job',
            name='category',
        ),
        migrations.RemoveField(
            model_name='job',
            name='employer',
        ),
        migrations.RemoveField(
            model_name='jobbrowsehistory',
            name='job',
        ),
        migrations.RenameIndex(
            model_name='jobbrowsehistory',
            new_name='jobs_jobbro_job_see_2d0b57_idx',
            old_name='jobs_jobbrow_job_see_8b8b0a_idx',
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='jobbookmark',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='application',
            name='job_info',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.jobinfo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobbookmark',
            name='job_info',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='jobs.jobinfo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobbrowsehistory',
            name='job_info',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='browse_history', to='jobs.jobinfo'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('job_info', 'job_seeker')},
        ),
        migrations.AlterUniqueTogether(
            name='jobbookmark',
            unique_together={('job_info', 'job_seeker')},
        ),
        migrations.AddField(
            model_name='jobinfo',
            name='job_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='jobs.jobpost', verbose_name='所属招聘公告'),
        ),
        migrations.RemoveField(
            model_name='application',
            name='job',
        ),
        migrations.RemoveField(
            model_name='jobbookmark',
            name='job',
        ),
        migrations.DeleteModel(
            name='Job',
        ),
    ]
