# Generated by Django 5.2.6 on 2025-09-12 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_jobinfo_jobpost_remove_job_category_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
