# Generated by Django 4.2.23 on 2025-09-12 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_delete_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='html_text',
            field=models.TextField(blank=True, null=True, verbose_name='招聘公告详情(html文本)'),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='source_url',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='招聘公告详情链接'),
        ),
    ]
